### ISSUE TITLE
Villagers Can't Become Fletchers (bug/suggestion)

### ISSUE THREAD

**Issue by Coraline77447** [Shadows-of-Fire/Apotheosis#285]
Hi, its me again but this time this is about the fletching table, I've built a custom swamp village that has two fletching tables in a custom  built fletcher house but in the same design as a plains fletcher house (but made out of oak wood and swamp willow wood, swamp willow wood is from better default biomes mod btw). 

When I cured a zombie villager while in creative mode while it was trapped in the fletcher house he couldn't find the fletching table because you've changed it for us players to use it instead of the villagers or for both the villagers and the players! Can you make the fletching table be used for both the villagers and the players please?...

Side note: Without Apotheosis mod when you build your own village that a villager that you either kidnapped from a village nearby or after being a villager zombie when cured can become a fletcher after finding the fletching table but when you build your own village and you do the same things as before while Apotheosis is installed is when the villagers can't find the fletching table to become a fletcher because the problem is that they don't see the fletching table at all cause apparently they're hard-coded to see the vanilla fletching table and not the one you've made some slight changes to it and they dont recognize it anymore which leaves your custom built village without any fletchers which leads to some players like me who'll be straight out of luck if some of us (like myself) really wants to trade with the flechers to say buy thier enchanted bow that may have a preffox (sorry for pronouncing that wrong but I cant really remember how to pronounce it...) that was added by Apotheosis mod while it could also have something  like Power III or higher even tho it's all completely random while having Apotheosis installed, that's what this report is all about.

**Comment by Elpximso** [comment]
Have the same issue with a mod called easy villagers, cant use the fletching table anyway possible :/

**Comment by Coraline77447** [comment]
Btw the world that I've discovered this issue on has been deleted already but until my latest issue with Apotheosis is resolved I'm not going to continue to play with Apotheosis...

**Comment by Shadows-of-Fire** [comment]
fixed in dev

**Comment by Coraline77447** [comment]
Just wondering but when will the next update be available? Since I do miss playing with Apotheosis since it's a good mod.

Also that my second issue with the mod is what's preventing me from playing with Apotheosis (even tho for the enchanting I would prefer to use the vanilla enchanting system than using a different enchanting system since I'm used to the old enchanting system anyways). 

Just read one of my other emails from ya that you said that whats causing my other issue with Apotheosis is actually coming from MVW (MoreVanillaWeapons).

Apparently it may or may not be a confliction/incompatibility since my second issue states that both Apotheosis and MVW aren't playing fair with each other. 

So how can we make them play nice with each other? (Why I said "we" is cause I would report that issue to the owner of MVW about it but doesn't hurt for you to help me out. (If you're not too busy that is)
Do you want both Apotheosis and MVW to play fair with each other? Or not? Cause I wanna help both mods to play fair with each other and that both are good mods to play with.
Even tho I'm not playing with MVW right now on my current modded world cause I want a different gaming experience without MVW but my next world will have MVW and hopefully Apotheosis whenever it gets updated with those fixes.)

**Comment by Coraline77447** [comment]
Hi, I was just wondering when will the update be released? Btw I'm in no rush for the update that's supposed to fix the issues that I had with Apotheosis. Take as much time as you need since I'm not trying to rush you to roll out the update at all, I just miss playing with this awesome mod while those problems are still preventing me from enjoying Apotheosis. Okay.
(I know I've already asked this before but that was months ago since I've been waiting patiently for the update this entire time while I've been playing modded MC. I hope I'm not annoying you tho....)

**Comment by Coraline77447** [comment]
Hi, it's me again. I would like to thank you for releasing the update that I and everyone was waiting for. Even though it was a long wait but the wait was worth it and while I was waiting I was just doing my normal thing as of playing modded minecraft as of keeping myself entertained and stuff while I was waiting for this update to arrive and now it has arrived and now I'll certainly install the update onto my current modded world that is named; Coraline World 2 1.16.5 (Modded) (This world's main theme is all about combat with melee weapons from Tinkers' Construct while it's in it's alpha stat for 1.16.5. Along with adventure with A.O.A (Advent of Ascension) aka Nevermine mod in it's beta state as of beta 4. Now with Apotheosis my adventures will be even better than ever before!)
Alrighty, I'm gonna keep lookin for updates to mods I play with and will get started when I'm finished. Bye! Thanks again!
